anggrio/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('confirm', views.confirmationPage, name='confirmationPage'),
]

story7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('anggrio.urls')),
]

anggrio/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    name = models.CharField(max_length=255)
    status = models.CharField(max_length=255)

    def __str__(self):
        return self.status

anggrio/forms.py
from django.forms import ModelForm, TextInput, Select
from .models import Status

class StatusForm(ModelForm):
    class Meta:
        model = Status
        fields = ['name', 'status']
        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'status': TextInput(attrs={'class': 'form-control'}),
        }

anggrio/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .forms import StatusForm
from .models import Status

# Create your views here.
def homepage(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = StatusForm(request.POST)
    # if a GET (or any other method) we'll create a blank form
    else:
        form = StatusForm()

    status = Status.objects.all()
    return render(request, 'homepage.html', {'status': status, 'form': form})

def confirmationPage(request):
    if request.method == 'POST':
        if 'confirm' in request.POST:
            form = StatusForm(request.POST)
            if form.is_valid():
                name = form.cleaned_data['name']
                status = form.cleaned_data['status']
                return render(request, 'confirmationPage.html', {'name': name, 'status': status})
        elif 'continue' in request.POST:
            form = StatusForm(request.POST)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect('/')
        else:
            return HttpResponseRedirect('/')

    return render(request, 'confirmationPage.html', {'name': "", "status": ""})
    

anggrio/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <base href="/">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  {% block title %}
  {% endblock %}
</head>
<body>
  {% block content %}
  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

  <script>
    function change() {
      var x = document.getElementsByTagName("table");
      var i;
      if (x[0].style.color=="blue") {
        for (i=0;i<x.length;i++) {
          x[i].style.color = "white";
          x[i].style.backgroundColor = "rgba(52, 58, 64, 1)"
        }
      } else {
        for (i=0;i<x.length;i++) {
          x[i].style.color = "blue";
          x[i].style.backgroundColor = "#89CFF0"
        }
      }
    }
  </script>
</body>

anggrio/templates/confirmationPage.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Anggrio Wildanhadi Sutopo's Confirmation Page</title>
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="text-center">
        <strong>Please confirm your name and status</strong>
    </h1>
    <h3 id="name">Name: {{ name }}</h3>
    <h3 id="status">Status: {{ status }}</h3>
    <form method="POST" action="{% url 'confirmationPage' %}">
        {% csrf_token %}
        <input type="hidden" name="name" id="id_name" value="{{ name }}">
        <input type="hidden" name="status" id="id_status" value="{{ status }}">
        <br>
        <div class="text-right">
            <button id="back">Go Back</button>
            <input class="submit_button" type="Submit" name="continue" value="Submit Status" style="display: inline-block;" />
        </div>
    </form>
</div>
{% endblock %}

anggrio/templates/homepage.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Anggrio Wildanhadi Sutopo's Status Page</title>
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="text-center">
        <strong>Hello, how are you?</strong>
    </h1>
    <form method="POST" action="{% url 'confirmationPage' %}">
        {% csrf_token %}
        <label for="{{ form.name.id_for_label }}">Name</label>
        {{ form.name }}
        <label for="{{ form.status.id_for_label }}">Status</label>
        {{ form.status }}
        <br>
        <div class="text-right">
            <button type="submit" name="confirm">Submit Status</button>
        </div>
    </form>
    <div class="text-left">
        <button id="change" onclick="change()">Change Color</button>
    </div>
    <h1 class="text-center">
        Status
    </h1>
    <table class="table table-striped table-dark">
        <thead>
            <tr>
                <th scope="col" style="width: 25%">Name</th>
                <th scope="col">Status</th>
            </tr>
        </thead>
        <tbody>
            {% for s in status %}
            <tr>
                <td id="storedName">{{ s.name }}</th>
                <td id="storedStatus">{{ s.status }}</th>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}